language: node_js
node_js:
- '4'
script: npm run lint
notifications:
  slack:
    secure: t1GAXXA3Q4hSanZE0yFqD5uUXFBJ4LGHHhGgzTQQngH/tS+O/dREJ/5qNciQzakQSwi5Yjx0psdrr7ISmydnLfhSIR0HwfXnM2LlZMfzjb2XT9X4pRNV0AgarqATk9nMxlAf7MEx4qWl/+RL68aO55ifMNec/mWerEssyCiOAcVTpBYDpar2rAmg4ob0MGdIrkhT8o7IyqQNK6oFazp24XTX9G3upQNMaoUgUe99HbbtEwxONODVgy0KFqXrLW0puWPWNPWzsl4xhjs9hpFoDisNtZiFy0IMrCwY+IuEN4avXG0uUsK7pX2eCykOLB3JEN9llT5DtPLn9dFDQ09A2Opi7xdIqbPYxOcu5ZgPq8AYY5NqD/IogLoM9pV4VSMROj5QAZuqv+vqrxj87ac+XgEg2i3kc4oVOsa54Vv0+XTz08+LQe6PlCouugHLGTPYwObHHpy9UaCTDr/zvlcnvhbXYfeL+TgHcDypifQ3fjOM6L2tq7LzwdsBghZZLiwr7Xesw1nKDwzHY/OzcwBrrJbkYrthCMNaJ+C7COsp0pICKQVQHPXzrmiAz+4kt88SYHJWCaGOOEcysBs8Inw1Pi+FFUMOcDWcH6oxAAAGhJtDqovKVXsgHflGbuTK1JjUPukla5OTbFsL/rY+zJDho7g/PITjnJLN5KicbnXKWNE=
    on_success: always
    on_failure: always
